# Generated by Django 4.2.9 on 2024-04-09 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import works.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='project_this_wk',
            field=models.TextField(verbose_name='This Week Project'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('tcp_ip', models.CharField(blank=True, max_length=150)),
                ('writer', models.ForeignKey(default=works.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='review', to=settings.AUTH_USER_MODEL))
            ],
        ),
    ]
