# Generated by Django 4.2.9 on 2024-04-09 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import works.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0002_alter_weeklyreport_project_this_wk_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('tcp_ip', models.CharField(blank=True, max_length=150)),
                ('file1', models.FileField(blank=True, null=True, upload_to='paper_templates/')),
                ('file2', models.FileField(blank=True, null=True, upload_to='paper_templates/')),
                ('writer', models.ForeignKey(default=works.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paper_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
