# Generated by Django 4.2.9 on 2024-02-25 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import publications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('status', models.IntegerField(null=True)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('writer', models.CharField(max_length=100)),
                ('visit', models.IntegerField(default=1)),
                ('tcp_ip', models.CharField(max_length=100, null=True)),
                ('patent_type', models.IntegerField(choices=[(1, 'International'), (2, 'Domestic')], default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('journal_name', models.CharField(max_length=100, null=True)),
                ('abstract', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Preparation'), (2, 'Submitted'), (3, 'Under Review'), (4, 'Accepted'), (5, 'Published'), (6, 'Best Paper'), (7, 'Minor Revision'), (8, 'Rejected')], default=1, null=True)),
                ('journal_type', models.IntegerField(choices=[(1, 'International'), (2, 'Domestic')], default=1, null=True)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('visit', models.IntegerField(default=1)),
                ('ack', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_year', models.CharField(blank=True, max_length=10, null=True)),
                ('all_authors', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='journals/')),
                ('cite', models.CharField(blank=True, max_length=400)),
                ('writer', models.ForeignKey(default=publications.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('conference_name', models.CharField(max_length=100, null=True)),
                ('abstract', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Preparation'), (2, 'Submitted'), (3, 'Under Review'), (4, 'Accepted'), (5, 'Published'), (6, 'Best Paper'), (7, 'Minor Revision'), (8, 'Rejected')], default=1, null=True)),
                ('conference_type', models.IntegerField(choices=[(1, 'International'), (2, 'Domestic')], default=1, null=True)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('visit', models.IntegerField(default=1)),
                ('ack', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_year', models.CharField(blank=True, max_length=10, null=True)),
                ('all_authors', models.CharField(blank=True, max_length=500, null=True)),
                ('cite', models.CharField(blank=True, max_length=400)),
                ('file', models.FileField(blank=True, null=True, upload_to='conference/')),
                ('writer', models.ForeignKey(default=publications.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('ref', models.CharField(blank=True, max_length=100)),
                ('abstract', models.TextField(blank=True)),
                ('visit', models.IntegerField(blank=True, default=1)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file1', models.FileField(blank=True, null=True, upload_to='books/')),
                ('file2', models.FileField(blank=True, null=True, upload_to='books/')),
                ('writer', models.ForeignKey(default=publications.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
