# Generated by Django 4.2.9 on 2024-01-18 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0014_alter_patent_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('abstract', models.TextField(null=True)),
                ('visit', models.IntegerField(default=1)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='books/')),
                ('file2', models.FileField(blank=True, null=True, upload_to='books/')),
                ('writer', models.ForeignKey(default=publications.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
