# Generated by Django 4.2.9 on 2024-01-19 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='abstract',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='visit',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='write_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
