# Generated by Django 4.2.9 on 2024-01-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_alter_book_abstract_alter_book_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='cite',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='journal',
            name='cite',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
