# Generated by Django 4.2.9 on 2024-02-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_conference_cite_journal_cite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='extras',
        ),
        migrations.AlterField(
            model_name='conference',
            name='all_authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='all_authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
