# Generated by Django 4.2.9 on 2024-02-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_remove_conference_extras_remove_journal_extras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='cite',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='journal',
            name='cite',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
