# Generated by Django 4.2.9 on 2024-02-25 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import works.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='From')),
                ('to_dt', models.DateTimeField(default=works.models.next_friday, verbose_name='Till')),
                ('paper_progress', models.TextField(verbose_name='Paper Progress')),
                ('paper_prog_percent', models.IntegerField(verbose_name='Paper Progress Percent')),
                ('paper_last_wk', models.TextField(verbose_name='Last Week Paper')),
                ('paper_this_wk', models.TextField(verbose_name='This Week Paper')),
                ('project_progress', models.TextField(verbose_name='Project Progress')),
                ('project_prog_percent', models.IntegerField(verbose_name='Paper Progress Percent')),
                ('project_last_wk', models.TextField(verbose_name='Last Week Project')),
                ('project_this_wk', models.TextField(verbose_name='Last Week Project')),
                ('mnth_gls', models.TextField(verbose_name='Monthly Goals')),
                ('annl_gls', models.TextField(verbose_name='Annual Goals')),
                ('user', models.CharField(blank=True, null=True)),
                ('writer', models.ForeignKey(default=works.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.IntegerField(blank=True, default=1)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='seminar/')),
                ('file2', models.FileField(blank=True, null=True, upload_to='seminar/')),
                ('title', models.CharField(max_length=500, null=True)),
                ('ref', models.CharField(blank=True, max_length=150)),
                ('tcp_ip', models.CharField(blank=True, max_length=150)),
                ('writer', models.ForeignKey(default=works.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seminar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostDocReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='From Date')),
                ('to_dt', models.DateTimeField(default=works.models.next_friday, verbose_name='Till')),
                ('paper_progress', models.TextField(verbose_name='Paper Progress')),
                ('project_progress', models.TextField(verbose_name='Project Progress')),
                ('mnth_gls', models.TextField(verbose_name='Monthly Goals')),
                ('annl_gls', models.TextField(verbose_name='Annual Goals')),
                ('user', models.CharField(blank=True, null=True)),
                ('writer', models.ForeignKey(default=works.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_doc_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
