# Generated by Django 4.2.9 on 2024-01-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_seminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='ref',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='tcp_ip',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
