# Generated by Django 4.2.9 on 2024-01-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_alter_seminar_ref_alter_seminar_tcp_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
