# Generated by Django 4.2.9 on 2024-01-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_alter_seminar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='is_post_doc',
        ),
    ]
