# Generated by Django 4.2.9 on 2024-02-14 05:23

from django.db import migrations, models
import django.utils.timezone
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_remove_weeklyreport_is_post_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdocreport',
            name='to_dt',
            field=models.DateTimeField(default=works.models.next_friday, verbose_name='Till'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='fr_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='to_dt',
            field=models.DateTimeField(default=works.models.next_friday, verbose_name='Till'),
        ),
    ]
